// GENERATED by scripts/photos.ts from its CUTS table — do not edit by hand;
// change the table and run `nix shell nixpkgs#vips -c npm run photos`.
import hero_560_avif from "../../../assets/photos/hero-560.avif";
import hero_1056_avif from "../../../assets/photos/hero-1056.avif";
import hero_560_webp from "../../../assets/photos/hero-560.webp";
import hero_1056_webp from "../../../assets/photos/hero-1056.webp";
import svc_deep_400_avif from "../../../assets/photos/svc-deep-400.avif";
import svc_deep_720_avif from "../../../assets/photos/svc-deep-720.avif";
import svc_deep_400_webp from "../../../assets/photos/svc-deep-400.webp";
import svc_deep_720_webp from "../../../assets/photos/svc-deep-720.webp";
import svc_upholstery_400_avif from "../../../assets/photos/svc-upholstery-400.avif";
import svc_upholstery_720_avif from "../../../assets/photos/svc-upholstery-720.avif";
import svc_upholstery_400_webp from "../../../assets/photos/svc-upholstery-400.webp";
import svc_upholstery_720_webp from "../../../assets/photos/svc-upholstery-720.webp";
import svc_exterior_400_avif from "../../../assets/photos/svc-exterior-400.avif";
import svc_exterior_499_avif from "../../../assets/photos/svc-exterior-499.avif";
import svc_exterior_400_webp from "../../../assets/photos/svc-exterior-400.webp";
import svc_exterior_499_webp from "../../../assets/photos/svc-exterior-499.webp";
import svc_other_400_avif from "../../../assets/photos/svc-other-400.avif";
import svc_other_720_avif from "../../../assets/photos/svc-other-720.avif";
import svc_other_400_webp from "../../../assets/photos/svc-other-400.webp";
import svc_other_720_webp from "../../../assets/photos/svc-other-720.webp";
import sofa_before_480_avif from "../../../assets/photos/sofa-before-480.avif";
import sofa_before_717_avif from "../../../assets/photos/sofa-before-717.avif";
import sofa_before_480_webp from "../../../assets/photos/sofa-before-480.webp";
import sofa_before_717_webp from "../../../assets/photos/sofa-before-717.webp";
import sofa_after_480_avif from "../../../assets/photos/sofa-after-480.avif";
import sofa_after_717_avif from "../../../assets/photos/sofa-after-717.avif";
import sofa_after_480_webp from "../../../assets/photos/sofa-after-480.webp";
import sofa_after_717_webp from "../../../assets/photos/sofa-after-717.webp";
import sofa_thumb_144_avif from "../../../assets/photos/sofa-thumb-144.avif";
import sofa_thumb_144_webp from "../../../assets/photos/sofa-thumb-144.webp";
import bathtub_before_480_avif from "../../../assets/photos/bathtub-before-480.avif";
import bathtub_before_519_avif from "../../../assets/photos/bathtub-before-519.avif";
import bathtub_before_480_webp from "../../../assets/photos/bathtub-before-480.webp";
import bathtub_before_519_webp from "../../../assets/photos/bathtub-before-519.webp";
import bathtub_after_480_avif from "../../../assets/photos/bathtub-after-480.avif";
import bathtub_after_519_avif from "../../../assets/photos/bathtub-after-519.avif";
import bathtub_after_480_webp from "../../../assets/photos/bathtub-after-480.webp";
import bathtub_after_519_webp from "../../../assets/photos/bathtub-after-519.webp";
import bathtub_thumb_144_avif from "../../../assets/photos/bathtub-thumb-144.avif";
import bathtub_thumb_144_webp from "../../../assets/photos/bathtub-thumb-144.webp";
import carpet_before_480_avif from "../../../assets/photos/carpet-before-480.avif";
import carpet_before_491_avif from "../../../assets/photos/carpet-before-491.avif";
import carpet_before_480_webp from "../../../assets/photos/carpet-before-480.webp";
import carpet_before_491_webp from "../../../assets/photos/carpet-before-491.webp";
import carpet_after_480_avif from "../../../assets/photos/carpet-after-480.avif";
import carpet_after_491_avif from "../../../assets/photos/carpet-after-491.avif";
import carpet_after_480_webp from "../../../assets/photos/carpet-after-480.webp";
import carpet_after_491_webp from "../../../assets/photos/carpet-after-491.webp";
import carpet_thumb_144_avif from "../../../assets/photos/carpet-thumb-144.avif";
import carpet_thumb_144_webp from "../../../assets/photos/carpet-thumb-144.webp";
import driveway_before_480_avif from "../../../assets/photos/driveway-before-480.avif";
import driveway_before_539_avif from "../../../assets/photos/driveway-before-539.avif";
import driveway_before_480_webp from "../../../assets/photos/driveway-before-480.webp";
import driveway_before_539_webp from "../../../assets/photos/driveway-before-539.webp";
import driveway_after_480_avif from "../../../assets/photos/driveway-after-480.avif";
import driveway_after_539_avif from "../../../assets/photos/driveway-after-539.avif";
import driveway_after_480_webp from "../../../assets/photos/driveway-after-480.webp";
import driveway_after_539_webp from "../../../assets/photos/driveway-after-539.webp";
import driveway_thumb_144_avif from "../../../assets/photos/driveway-thumb-144.avif";
import driveway_thumb_144_webp from "../../../assets/photos/driveway-thumb-144.webp";
import mattress_before_480_avif from "../../../assets/photos/mattress-before-480.avif";
import mattress_before_549_avif from "../../../assets/photos/mattress-before-549.avif";
import mattress_before_480_webp from "../../../assets/photos/mattress-before-480.webp";
import mattress_before_549_webp from "../../../assets/photos/mattress-before-549.webp";
import mattress_after_480_avif from "../../../assets/photos/mattress-after-480.avif";
import mattress_after_549_avif from "../../../assets/photos/mattress-after-549.avif";
import mattress_after_480_webp from "../../../assets/photos/mattress-after-480.webp";
import mattress_after_549_webp from "../../../assets/photos/mattress-after-549.webp";
import mattress_thumb_144_avif from "../../../assets/photos/mattress-thumb-144.avif";
import mattress_thumb_144_webp from "../../../assets/photos/mattress-thumb-144.webp";
import recliner_before_461_avif from "../../../assets/photos/recliner-before-461.avif";
import recliner_before_461_webp from "../../../assets/photos/recliner-before-461.webp";
import recliner_after_461_avif from "../../../assets/photos/recliner-after-461.avif";
import recliner_after_461_webp from "../../../assets/photos/recliner-after-461.webp";
import recliner_thumb_144_avif from "../../../assets/photos/recliner-thumb-144.avif";
import recliner_thumb_144_webp from "../../../assets/photos/recliner-thumb-144.webp";

/** Each photo's `srcset` per format, for a `<picture>`'s `<source>`s, and its `<img>` fallback. */
export const PHOTO_SETS = {
  "hero": {
    avif: [`${hero_560_avif.src} 560w`, `${hero_1056_avif.src} 1056w`].join(", "),
    webp: [`${hero_560_webp.src} 560w`, `${hero_1056_webp.src} 1056w`].join(", "),
    src: hero_1056_webp.src,
  },
  "svc-deep": {
    avif: [`${svc_deep_400_avif.src} 400w`, `${svc_deep_720_avif.src} 720w`].join(", "),
    webp: [`${svc_deep_400_webp.src} 400w`, `${svc_deep_720_webp.src} 720w`].join(", "),
    src: svc_deep_720_webp.src,
  },
  "svc-upholstery": {
    avif: [`${svc_upholstery_400_avif.src} 400w`, `${svc_upholstery_720_avif.src} 720w`].join(", "),
    webp: [`${svc_upholstery_400_webp.src} 400w`, `${svc_upholstery_720_webp.src} 720w`].join(", "),
    src: svc_upholstery_720_webp.src,
  },
  "svc-exterior": {
    avif: [`${svc_exterior_400_avif.src} 400w`, `${svc_exterior_499_avif.src} 499w`].join(", "),
    webp: [`${svc_exterior_400_webp.src} 400w`, `${svc_exterior_499_webp.src} 499w`].join(", "),
    src: svc_exterior_499_webp.src,
  },
  "svc-other": {
    avif: [`${svc_other_400_avif.src} 400w`, `${svc_other_720_avif.src} 720w`].join(", "),
    webp: [`${svc_other_400_webp.src} 400w`, `${svc_other_720_webp.src} 720w`].join(", "),
    src: svc_other_720_webp.src,
  },
  "sofa-before": {
    avif: [`${sofa_before_480_avif.src} 480w`, `${sofa_before_717_avif.src} 717w`].join(", "),
    webp: [`${sofa_before_480_webp.src} 480w`, `${sofa_before_717_webp.src} 717w`].join(", "),
    src: sofa_before_717_webp.src,
  },
  "sofa-after": {
    avif: [`${sofa_after_480_avif.src} 480w`, `${sofa_after_717_avif.src} 717w`].join(", "),
    webp: [`${sofa_after_480_webp.src} 480w`, `${sofa_after_717_webp.src} 717w`].join(", "),
    src: sofa_after_717_webp.src,
  },
  "sofa-thumb": {
    avif: [`${sofa_thumb_144_avif.src} 144w`].join(", "),
    webp: [`${sofa_thumb_144_webp.src} 144w`].join(", "),
    src: sofa_thumb_144_webp.src,
  },
  "bathtub-before": {
    avif: [`${bathtub_before_480_avif.src} 480w`, `${bathtub_before_519_avif.src} 519w`].join(", "),
    webp: [`${bathtub_before_480_webp.src} 480w`, `${bathtub_before_519_webp.src} 519w`].join(", "),
    src: bathtub_before_519_webp.src,
  },
  "bathtub-after": {
    avif: [`${bathtub_after_480_avif.src} 480w`, `${bathtub_after_519_avif.src} 519w`].join(", "),
    webp: [`${bathtub_after_480_webp.src} 480w`, `${bathtub_after_519_webp.src} 519w`].join(", "),
    src: bathtub_after_519_webp.src,
  },
  "bathtub-thumb": {
    avif: [`${bathtub_thumb_144_avif.src} 144w`].join(", "),
    webp: [`${bathtub_thumb_144_webp.src} 144w`].join(", "),
    src: bathtub_thumb_144_webp.src,
  },
  "carpet-before": {
    avif: [`${carpet_before_480_avif.src} 480w`, `${carpet_before_491_avif.src} 491w`].join(", "),
    webp: [`${carpet_before_480_webp.src} 480w`, `${carpet_before_491_webp.src} 491w`].join(", "),
    src: carpet_before_491_webp.src,
  },
  "carpet-after": {
    avif: [`${carpet_after_480_avif.src} 480w`, `${carpet_after_491_avif.src} 491w`].join(", "),
    webp: [`${carpet_after_480_webp.src} 480w`, `${carpet_after_491_webp.src} 491w`].join(", "),
    src: carpet_after_491_webp.src,
  },
  "carpet-thumb": {
    avif: [`${carpet_thumb_144_avif.src} 144w`].join(", "),
    webp: [`${carpet_thumb_144_webp.src} 144w`].join(", "),
    src: carpet_thumb_144_webp.src,
  },
  "driveway-before": {
    avif: [`${driveway_before_480_avif.src} 480w`, `${driveway_before_539_avif.src} 539w`].join(", "),
    webp: [`${driveway_before_480_webp.src} 480w`, `${driveway_before_539_webp.src} 539w`].join(", "),
    src: driveway_before_539_webp.src,
  },
  "driveway-after": {
    avif: [`${driveway_after_480_avif.src} 480w`, `${driveway_after_539_avif.src} 539w`].join(", "),
    webp: [`${driveway_after_480_webp.src} 480w`, `${driveway_after_539_webp.src} 539w`].join(", "),
    src: driveway_after_539_webp.src,
  },
  "driveway-thumb": {
    avif: [`${driveway_thumb_144_avif.src} 144w`].join(", "),
    webp: [`${driveway_thumb_144_webp.src} 144w`].join(", "),
    src: driveway_thumb_144_webp.src,
  },
  "mattress-before": {
    avif: [`${mattress_before_480_avif.src} 480w`, `${mattress_before_549_avif.src} 549w`].join(", "),
    webp: [`${mattress_before_480_webp.src} 480w`, `${mattress_before_549_webp.src} 549w`].join(", "),
    src: mattress_before_549_webp.src,
  },
  "mattress-after": {
    avif: [`${mattress_after_480_avif.src} 480w`, `${mattress_after_549_avif.src} 549w`].join(", "),
    webp: [`${mattress_after_480_webp.src} 480w`, `${mattress_after_549_webp.src} 549w`].join(", "),
    src: mattress_after_549_webp.src,
  },
  "mattress-thumb": {
    avif: [`${mattress_thumb_144_avif.src} 144w`].join(", "),
    webp: [`${mattress_thumb_144_webp.src} 144w`].join(", "),
    src: mattress_thumb_144_webp.src,
  },
  "recliner-before": {
    avif: [`${recliner_before_461_avif.src} 461w`].join(", "),
    webp: [`${recliner_before_461_webp.src} 461w`].join(", "),
    src: recliner_before_461_webp.src,
  },
  "recliner-after": {
    avif: [`${recliner_after_461_avif.src} 461w`].join(", "),
    webp: [`${recliner_after_461_webp.src} 461w`].join(", "),
    src: recliner_after_461_webp.src,
  },
  "recliner-thumb": {
    avif: [`${recliner_thumb_144_avif.src} 144w`].join(", "),
    webp: [`${recliner_thumb_144_webp.src} 144w`].join(", "),
    src: recliner_thumb_144_webp.src,
  },
} as const;

export type PhotoStem = keyof typeof PHOTO_SETS;
