// GENERATED by scripts/photos.ts from its CUTS table — do not edit by hand;
// change the table and run `nix shell nixpkgs#vips -c npm run photos`.
import hero_1800_avif from "../../../assets/photos/hero-1800.avif";
import hero_1800_webp from "../../../assets/photos/hero-1800.webp";
import avatar_1_36_avif from "../../../assets/photos/avatar-1-36.avif";
import avatar_1_72_avif from "../../../assets/photos/avatar-1-72.avif";
import avatar_1_36_webp from "../../../assets/photos/avatar-1-36.webp";
import avatar_1_72_webp from "../../../assets/photos/avatar-1-72.webp";
import avatar_2_36_avif from "../../../assets/photos/avatar-2-36.avif";
import avatar_2_72_avif from "../../../assets/photos/avatar-2-72.avif";
import avatar_2_36_webp from "../../../assets/photos/avatar-2-36.webp";
import avatar_2_72_webp from "../../../assets/photos/avatar-2-72.webp";
import avatar_3_36_avif from "../../../assets/photos/avatar-3-36.avif";
import avatar_3_72_avif from "../../../assets/photos/avatar-3-72.avif";
import avatar_3_36_webp from "../../../assets/photos/avatar-3-36.webp";
import avatar_3_72_webp from "../../../assets/photos/avatar-3-72.webp";
import avatar_4_36_avif from "../../../assets/photos/avatar-4-36.avif";
import avatar_4_72_avif from "../../../assets/photos/avatar-4-72.avif";
import avatar_4_36_webp from "../../../assets/photos/avatar-4-36.webp";
import avatar_4_72_webp from "../../../assets/photos/avatar-4-72.webp";
import service_standard_358_avif from "../../../assets/photos/service-standard-358.avif";
import service_standard_700_avif from "../../../assets/photos/service-standard-700.avif";
import service_standard_358_webp from "../../../assets/photos/service-standard-358.webp";
import service_standard_700_webp from "../../../assets/photos/service-standard-700.webp";
import service_deep_358_avif from "../../../assets/photos/service-deep-358.avif";
import service_deep_700_avif from "../../../assets/photos/service-deep-700.avif";
import service_deep_358_webp from "../../../assets/photos/service-deep-358.webp";
import service_deep_700_webp from "../../../assets/photos/service-deep-700.webp";
import service_move_358_avif from "../../../assets/photos/service-move-358.avif";
import service_move_700_avif from "../../../assets/photos/service-move-700.avif";
import service_move_358_webp from "../../../assets/photos/service-move-358.webp";
import service_move_700_webp from "../../../assets/photos/service-move-700.webp";
import service_post_construction_358_avif from "../../../assets/photos/service-post-construction-358.avif";
import service_post_construction_700_avif from "../../../assets/photos/service-post-construction-700.avif";
import service_post_construction_358_webp from "../../../assets/photos/service-post-construction-358.webp";
import service_post_construction_700_webp from "../../../assets/photos/service-post-construction-700.webp";
import review_amanda_result_360_avif from "../../../assets/photos/review-amanda-result-360.avif";
import review_amanda_result_720_avif from "../../../assets/photos/review-amanda-result-720.avif";
import review_amanda_result_360_webp from "../../../assets/photos/review-amanda-result-360.webp";
import review_amanda_result_720_webp from "../../../assets/photos/review-amanda-result-720.webp";
import review_amanda_job_320_avif from "../../../assets/photos/review-amanda-job-320.avif";
import review_amanda_job_640_avif from "../../../assets/photos/review-amanda-job-640.avif";
import review_amanda_job_320_webp from "../../../assets/photos/review-amanda-job-320.webp";
import review_amanda_job_640_webp from "../../../assets/photos/review-amanda-job-640.webp";
import review_marcus_result_360_avif from "../../../assets/photos/review-marcus-result-360.avif";
import review_marcus_result_720_avif from "../../../assets/photos/review-marcus-result-720.avif";
import review_marcus_result_360_webp from "../../../assets/photos/review-marcus-result-360.webp";
import review_marcus_result_720_webp from "../../../assets/photos/review-marcus-result-720.webp";
import review_marcus_job_320_avif from "../../../assets/photos/review-marcus-job-320.avif";
import review_marcus_job_640_avif from "../../../assets/photos/review-marcus-job-640.avif";
import review_marcus_job_320_webp from "../../../assets/photos/review-marcus-job-320.webp";
import review_marcus_job_640_webp from "../../../assets/photos/review-marcus-job-640.webp";
import review_priya_result_360_avif from "../../../assets/photos/review-priya-result-360.avif";
import review_priya_result_720_avif from "../../../assets/photos/review-priya-result-720.avif";
import review_priya_result_360_webp from "../../../assets/photos/review-priya-result-360.webp";
import review_priya_result_720_webp from "../../../assets/photos/review-priya-result-720.webp";
import review_priya_job_320_avif from "../../../assets/photos/review-priya-job-320.avif";
import review_priya_job_640_avif from "../../../assets/photos/review-priya-job-640.avif";
import review_priya_job_320_webp from "../../../assets/photos/review-priya-job-320.webp";
import review_priya_job_640_webp from "../../../assets/photos/review-priya-job-640.webp";

/** Each photo's `srcset` per format, for a `<picture>`'s `<source>`s, and its `<img>` fallback. */
export const PHOTO_SETS = {
  "hero": {
    avif: [`${hero_1800_avif.src} 1800w`].join(", "),
    webp: [`${hero_1800_webp.src} 1800w`].join(", "),
    src: hero_1800_webp.src,
  },
  "avatar-1": {
    avif: [`${avatar_1_36_avif.src} 36w`, `${avatar_1_72_avif.src} 72w`].join(", "),
    webp: [`${avatar_1_36_webp.src} 36w`, `${avatar_1_72_webp.src} 72w`].join(", "),
    src: avatar_1_72_webp.src,
  },
  "avatar-2": {
    avif: [`${avatar_2_36_avif.src} 36w`, `${avatar_2_72_avif.src} 72w`].join(", "),
    webp: [`${avatar_2_36_webp.src} 36w`, `${avatar_2_72_webp.src} 72w`].join(", "),
    src: avatar_2_72_webp.src,
  },
  "avatar-3": {
    avif: [`${avatar_3_36_avif.src} 36w`, `${avatar_3_72_avif.src} 72w`].join(", "),
    webp: [`${avatar_3_36_webp.src} 36w`, `${avatar_3_72_webp.src} 72w`].join(", "),
    src: avatar_3_72_webp.src,
  },
  "avatar-4": {
    avif: [`${avatar_4_36_avif.src} 36w`, `${avatar_4_72_avif.src} 72w`].join(", "),
    webp: [`${avatar_4_36_webp.src} 36w`, `${avatar_4_72_webp.src} 72w`].join(", "),
    src: avatar_4_72_webp.src,
  },
  "service-standard": {
    avif: [`${service_standard_358_avif.src} 358w`, `${service_standard_700_avif.src} 700w`].join(", "),
    webp: [`${service_standard_358_webp.src} 358w`, `${service_standard_700_webp.src} 700w`].join(", "),
    src: service_standard_700_webp.src,
  },
  "service-deep": {
    avif: [`${service_deep_358_avif.src} 358w`, `${service_deep_700_avif.src} 700w`].join(", "),
    webp: [`${service_deep_358_webp.src} 358w`, `${service_deep_700_webp.src} 700w`].join(", "),
    src: service_deep_700_webp.src,
  },
  "service-move": {
    avif: [`${service_move_358_avif.src} 358w`, `${service_move_700_avif.src} 700w`].join(", "),
    webp: [`${service_move_358_webp.src} 358w`, `${service_move_700_webp.src} 700w`].join(", "),
    src: service_move_700_webp.src,
  },
  "service-post-construction": {
    avif: [`${service_post_construction_358_avif.src} 358w`, `${service_post_construction_700_avif.src} 700w`].join(", "),
    webp: [`${service_post_construction_358_webp.src} 358w`, `${service_post_construction_700_webp.src} 700w`].join(", "),
    src: service_post_construction_700_webp.src,
  },
  "review-amanda-result": {
    avif: [`${review_amanda_result_360_avif.src} 360w`, `${review_amanda_result_720_avif.src} 720w`].join(", "),
    webp: [`${review_amanda_result_360_webp.src} 360w`, `${review_amanda_result_720_webp.src} 720w`].join(", "),
    src: review_amanda_result_720_webp.src,
  },
  "review-amanda-job": {
    avif: [`${review_amanda_job_320_avif.src} 320w`, `${review_amanda_job_640_avif.src} 640w`].join(", "),
    webp: [`${review_amanda_job_320_webp.src} 320w`, `${review_amanda_job_640_webp.src} 640w`].join(", "),
    src: review_amanda_job_640_webp.src,
  },
  "review-marcus-result": {
    avif: [`${review_marcus_result_360_avif.src} 360w`, `${review_marcus_result_720_avif.src} 720w`].join(", "),
    webp: [`${review_marcus_result_360_webp.src} 360w`, `${review_marcus_result_720_webp.src} 720w`].join(", "),
    src: review_marcus_result_720_webp.src,
  },
  "review-marcus-job": {
    avif: [`${review_marcus_job_320_avif.src} 320w`, `${review_marcus_job_640_avif.src} 640w`].join(", "),
    webp: [`${review_marcus_job_320_webp.src} 320w`, `${review_marcus_job_640_webp.src} 640w`].join(", "),
    src: review_marcus_job_640_webp.src,
  },
  "review-priya-result": {
    avif: [`${review_priya_result_360_avif.src} 360w`, `${review_priya_result_720_avif.src} 720w`].join(", "),
    webp: [`${review_priya_result_360_webp.src} 360w`, `${review_priya_result_720_webp.src} 720w`].join(", "),
    src: review_priya_result_720_webp.src,
  },
  "review-priya-job": {
    avif: [`${review_priya_job_320_avif.src} 320w`, `${review_priya_job_640_avif.src} 640w`].join(", "),
    webp: [`${review_priya_job_320_webp.src} 320w`, `${review_priya_job_640_webp.src} 640w`].join(", "),
    src: review_priya_job_640_webp.src,
  },
} as const;

export type PhotoStem = keyof typeof PHOTO_SETS;
