// Cuts the web variants of the Figma file's photos (`assets/design_images/`,
// exported from 1wXlPmnmOdKYPDWz6N5EB8) — AVIF and WebP at the widths the page
// lays them out at — into `assets/photos/`, and writes
// `src/shared/portfolio/photos.ts`, the module that imports them (so Next
// fingerprints each file) and spells their `srcset`s.
//
// Both outputs are committed: the Nix build runs no image encoder. Rerun after
// touching a photo or a line below; `tests/photos.test.ts` fails when the
// module no longer matches this plan.
//
//   nix shell nixpkgs#vips -c npm run photos
//
// Plain `node` runs it (type stripping), so it imports nothing but builtins.
import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface Crop {
  left: number;
  top: number;
  width: number;
  height: number;
}

interface Cut {
  /** Output name stem; the file is `<stem>-<width>.<format>`. */
  stem: string;
  source: string;
  widths: number[];
  /** A region of the source, in source pixels, taken before resizing. */
  crop?: Crop;
  /** Centre-cropped to a square: a thumbnail the layout shows square. */
  square?: boolean;
  /** Centre-cropped to this width : height — a frame the layout fixes the shape of. */
  aspect?: readonly [number, number];
}

/**
 * The plan: each photo at its laid-out width and twice it, never wider than
 * the source (an upscale is bytes with no detail in them). The frames crop
 * with `object-cover`, so the files keep the source's shape.
 */
export const CUTS: Cut[] = [
  // The hero's backdrop at 20 %: `object-cover` over a box taller than the hero
  // (1440 × 1071, 390 × 1796) draws it wider than the source, so the source's
  // full width is the only file.
  { stem: "hero", source: "hero-bg.jpg", widths: [1800] },
  // The hero's four faces, 36 px round.
  ...[1, 2, 3, 4].map(n => ({ stem: `avatar-${n}`, source: `avatar-${n}.jpg`, widths: [36, 72], square: true })),
  // Service cards: 268 × 176 on desktop, up to 358 × 176 on a phone.
  ...["standard", "deep", "move", "post-construction"].map(s => ({ stem: `service-${s}`, source: `service-${s}.jpg`, widths: [358, 700] })),
  // Review cards: the 16:9 result photo (360 wide) and the job photo, full
  // width of the card's body (320) and top-aligned in a 128 px strip.
  ...["amanda", "marcus", "priya"].flatMap(r => [
    { stem: `review-${r}-result`, source: `review-${r}-result.jpg`, widths: [360, 720] },
    { stem: `review-${r}-job`, source: `review-${r}-job.jpg`, widths: [320, 640] },
  ]),
];

export const FORMATS = [
  // Quality picked by eye against the png at 100 %; AVIF's scale runs lower.
  { ext: "avif", options: "[Q=52,effort=6,strip]" },
  { ext: "webp", options: "[Q=74,effort=6,strip]" },
] as const;

const SOURCES = "assets/design_images";
const WEB = "assets/photos";
const MODULE = "src/shared/portfolio/photos.ts";

const ident = (s: string) => s.replace(/[^a-z0-9]+/gi, "_");

/** The module text for {@link CUTS} — also what the test compares against. */
export function renderModule(): string {
  const imports: string[] = [];
  const sets: string[] = [];
  for (const cut of CUTS) {
    const byFormat = FORMATS.map(f => {
      const parts = cut.widths.map(w => {
        const name = ident(`${cut.stem}_${w}_${f.ext}`);
        imports.push(`import ${name} from "../../../${WEB}/${cut.stem}-${w}.${f.ext}";`);
        return `\`\${${name}.src} ${w}w\``;
      });
      return `    ${f.ext}: [${parts.join(", ")}].join(", "),`;
    });
    // The `<img>` fallback: the widest WebP, which every browser this site
    // supports decodes.
    const widest = ident(`${cut.stem}_${Math.max(...cut.widths)}_webp`);
    sets.push(`  "${cut.stem}": {\n${byFormat.join("\n")}\n    src: ${widest}.src,\n  },`);
  }
  return [
    "// GENERATED by scripts/photos.ts from its CUTS table — do not edit by hand;",
    "// change the table and run `nix shell nixpkgs#vips -c npm run photos`.",
    ...imports,
    "",
    "/** Each photo's `srcset` per format, for a `<picture>`'s `<source>`s, and its `<img>` fallback. */",
    "export const PHOTO_SETS = {",
    ...sets,
    "} as const;",
    "",
    "export type PhotoStem = keyof typeof PHOTO_SETS;",
    "",
  ].join("\n");
}

function cut(c: Cut, width: number, ext: string, options: string) {
  const out = join(WEB, `${c.stem}-${width}.${ext}`);
  let input = join(SOURCES, c.source);
  const tmp = join(WEB, `.${c.stem}-crop.v`);
  if (c.crop) {
    const { left, top, width: w, height: h } = c.crop;
    execFileSync("vips", ["extract_area", input, tmp, String(left), String(top), String(w), String(h)]);
    input = tmp;
  }
  const [w, h] = c.square ? [1, 1] : (c.aspect ?? [0, 0]);
  const shape = w > 0 ? ["--height", String(Math.round((width * h) / w)), "--crop", "centre"] : [];
  execFileSync("vips", ["thumbnail", input, `${out}${options}`, String(width), "--size", "down", ...shape]);
  if (c.crop) rmSync(tmp);
}

function main() {
  rmSync(WEB, { recursive: true, force: true });
  mkdirSync(WEB, { recursive: true });
  for (const c of CUTS) for (const w of c.widths) for (const f of FORMATS) cut(c, w, f.ext, f.options);
  mkdirSync("src/shared/portfolio", { recursive: true });
  writeFileSync(MODULE, renderModule());
  console.log(`✔ ${WEB}/ and ${MODULE}`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
